### ISSUE TITLE
Make the tool scriptable

### ISSUE THREAD

**Issue by mawinter69** [sapcc/nova-password#1]
Currently the nova-password tool produces a lot of output which makes parsing a bit tricky (using awk, to get only the third line and then hope that the 5th word is the password).
I propose something like a -b (--batch)  switch that will omit any output and just print the passwords in the order of given servers.

Our use case:
We want to setup windows machines with terraform. We need to attach disks to the instance but initially the disks are offline. So to take online and format the disks we need to remote-exec for which we need the Administrator password. Using an external data source we can get the password during the terraform run and the do a remote exec with winrm.

**Comment by kayrus** [comment]
@mawinter69  thanks for your request. In addition to the feature request, probably it's worth introducing an extra data source in [ccloud terraform provider](https://github.com/sapcc/terraform-provider-ccloud), e.g. `ccloud_compute_instance_password_v2`? This will allow to avoid any scripting in your terraform manifests. Thoughts?

**Comment by mawinter69** [comment]
We're using terraform 0.12.0 and use the default openstack provider. Is the ccloud provider compatible to it 0.12?
For those using your provider it most likely makes sense.
But there might be also other use cases outside of terraform where my proposal would be benefical.

**Comment by kayrus** [comment]
@mawinter69 yes, it supports 0.12. It is not a problem to introduce both features.

**Comment by kayrus** [comment]
> We want to setup windows machines with terraform. We need to attach disks to the instance but initially the disks are offline. So to take online and format the disks we need to remote-exec for which we need the Administrator password.

You can use automation resources in the ccloud provider for this case. It doesn't require Administrator password, see examples here:
https://github.com/sapcc/terraform-provider-ccloud/blob/master/website/docs/r/automation_v1.html.markdown
https://github.com/sapcc/terraform-provider-ccloud/blob/master/website/docs/r/automation_run_v1.html.markdown
