### ISSUE TITLE
Cannot logon vi RDP

### ISSUE THREAD

**Issue by stevenry1234** [sapcc/nova-password#7]
Hello

Ive been instructed to ask you to look into SPC 1113725851

thx

Stephen

**Comment by kayrus** [comment]
@stevenry1234 for windows you need to download the Windows version https://github.com/sapcc/nova-password/releases/download/v0.5.2/nova-password.exe version of the binary
I just verified it, and it should work fine. Also don't forget to source `openrc` file before the run.
![Screenshot_20210219_083254](https://user-images.githubusercontent.com/4047483/108472802-81e29f00-728d-11eb-96fe-34196c7836c4.png)

**Comment by stevenry1234** [comment]
Hello

seems url is;

https://github.com/sapcc/nova-password/releases/

i download the version without exe to allow download and then add exe but it doesent work??

![image](https://user-images.githubusercontent.com/79273550/108492437-10125180-729d-11eb-985c-c9d17ec9b139.png)

**Comment by stevenry1234** [comment]
ok ignore this i managed to download the exe version by changing download rules in windows

**Comment by kayrus** [comment]
There are tree versions for three OS'es:
* `nova-password` for Linux
* `nova-password_darwin` for MacOS
* `nova-password.exe` for Windows

**Comment by stevenry1234** [comment]
Hello

IM really struggling with this connection

im trying to connect from my windows laptop to my windows server instance? using below guide

https://documentation.global.cloud.sap/docs/start-instance-connect

i downloaded the nova-password and it runs fine. I downloaded also ope4nstack RC file

what  is this private key path below? where do i get it from?

**nova-password <instance_name> -i <private_key_path>**


also do I have to do below?  i ran the RC from dos and it opened a notepad file? DO i have to change some things there?

https://documentation.global.cloud.sap/docs/start-manage-instances-with-cli#openstack-rc-file


thx

Stephen
