### ISSUE TITLE
Issue logging on to windows server via my laptop...

### ISSUE THREAD

**Issue by stevenry1234** [sapcc/nova-password#8]
Hello

IM really struggling with this connection

im trying to connect from my windows laptop to my windows server instance?

i downloaded the nova-password and it runs fine. I downloaded also ope4nstack RC file

what is this private key path below? where do i get it from?

nova-password <instance_name> -i <private_key_path>

also do I have to do below? i ran the RC from dos and it opened a notepad file? DO i have to change some things there?

**Comment by kayrus** [comment]
> I downloaded also ope4nstack RC file

you also need to source it (e.g. run `.\openrc.ps1` in windows power shell, where `openrc.ps1` is a downloaded openrc file). see an example in readme: https://github.com/sapcc/nova-password#windows

> what is this private key path below? where do i get it from?

when you create a VM, you need to specify an RSA public key. Public key should be generated in advance from the RSA private key. RSA private key should be located on your local laptop.

**Comment by stevenry1234** [comment]
thank you... much.. !

i downloaded private key from 

![image](https://user-images.githubusercontent.com/79273550/108504181-66878c00-72ad-11eb-9288-ec4b1de54463.png)

and referenced it as below but it fails:

![image](https://user-images.githubusercontent.com/79273550/108503991-27f1d180-72ad-11eb-9096-9a22ccf2584d.png)

**Comment by stevenry1234** [comment]
Hello Again

see this error

![image](https://user-images.githubusercontent.com/79273550/108505303-114c7a00-72af-11eb-92f6-a0b510fedcdc.png)

thx

Stephen

**Comment by stevenry1234** [comment]
team

this isnt working, i cant post screenshots here
/Stephen
